server:
  port: 8899
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/974066621/springcloud
          search-paths: springcloud-config