spring: 
  application:
    name: springcloud-student-8080  
#eureka:
#  client: #客户端注册进eureka服务列表内
#    service-url: 
#       defaultZone: http://localhost:8001/eureka
#      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
#  instance:
#    instance-id: localhost      # 访问的ip地址
#    prefer-ip-address: true     #访问路径可以显示IP地址     
#info: 
#  app.name: springcloud-student-8080
#  company.name: liuyunzhe
#  build.artifactId: springcloud-student-8080
#  build.version: 0.0.1-SNAPSHOT