server:
  port: 8080
spring: 
  application:
    name: springcloud-student-8080
info:  
  app.name: springcloud-student-8080
  company.name: liuyunzhe
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
spring:
  profiles: dev
server:
  port: 8080
info: 
  app.name: 测试dev
  company.name: liuyunzhe
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
spring:
  profiles: test
server:
  port: 8080
info: 
  app.name: 测试test
  company.name: liuyunzhe
  build.artifactId: $project.artifactId$
  build.version: $project.version$


