server:
  port: 8081
  
spring: 
  application:
    name: springcloud-teacher-8081
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://localhost:8001/eureka
      #多机的时候向多个服务中进行注册defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: localhost      # 访问的ip地址 可以进行映射
    prefer-ip-address: true     #访问路径可以显示IP地址     
 
info: 
  app.name: springcloud-teacher-8081
  company.name: liuyunzhe
  build.artifactId: $project.artifactId$
  build.version: $project.version$